spring:
  datasource:
    url: jdbc:mysql://localhost:3306/password-encoder
    username: "password-encoder"
    password: "1qazxsw2"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
